name: Release

on:
  push:
    branches:
      - main

concurrency: release-${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    if: github.repository_owner == 'isaac-mason'
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=4096'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn

      - name: Build Packages
        run: yarn build

      - name: Test
        run: yarn test

      # release
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn version
          publish: yarn publish
          commit: 'chore(changeset): release packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
